---
- name: "Add NodeJs"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "Install NodeJs 13"
  become: true
  apt:
    name: ["nodejs"]
    update_cache: yes

- name: "Install PM2 globally"
  npm:
    name: pm2
    global: yes
