---
- name: "Add NodeJs"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | bash -

- name: "Install NodeJs 18"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 globally"
  npm:
    name: pm2
    global: yes
