---
- name: "create udapeople dir"
  file:
    path: /home/ubuntu/udapeople
    state: directory

- name: "unarchive backend files"
  unarchive:
    src: "../../../../../artifact.tar.gz"
    dest: "home/ubuntu/udapeople"

- name: "execute app with pm2"
  shell: |
    cd home/ubuntu/udapeople
    npm install
    cd ./dist
    pm2 stop default
    pm2 start main.js

  